alias clearhist='history -c && history -w'
alias egrep='grep -E --color=auto'
alias fgrep='grep -F --color=auto'
alias grep='grep --color=auto'
alias ll='lsd -la'
alias llt='lsd --tree -la'
alias ls='lsd'
alias tree='lsd --tree'
