#! /bin/bash

# bspwmrc for Meowix Linux live CD

# Set up workspaces
bspc monitor -d One Two Three Four Five Six Seven Eight Nine Ten

# Set the border width
bspc config border_width         2

# Set the window gap size
bspc config window_gap           12

# Set the split ratio
bspc config split_ratio          0.5

# Switch to monocle layout if there is only one window on screen
bspc config single_monocle       true

# Disable borders for monocle
bspc config borderless_monocle   true

# Disable gaps for monocle
bspc config gapless_monocle      true

# Focus windows when the pointer hovers over them
bspc config focus_follows_pointer true

# Set the default cursor
xsetroot -cursor_name left_ptr

# Set the theme colors
bspc config normal_border_color "#cba6f7"
bspc config active_border_color "#cba6f7"
bspc config focused_border_color "#f5c2e7"

# Startup applications
pgrep -x sxhkd > /dev/null || sxhkd & # Hotkey daemon
feh --bg-fill ~/Pictures/wallpaper.png & # Manages the wallpaper
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & # Polkit agent (basically sudo but GUI)
dunst & # Notificaton daemon
start-polybar & # Status bar
